
- name: Install starting packages
  package: name={{item}} state=installed
  with_items:
    - build-essential
    - unzip
    - software-properties-common


#
#
# Add more repos
#
#
- name: Add deadsnakes repo (Ubuntu 14.04)
  command: add-apt-repository ppa:fkrull/deadsnakes creates=/etc/apt/sources.list.d/fkrull-deadsnakes-trusty.list
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: Add trusty-media repo (Ubuntu 14.04)
  command: add-apt-repository ppa:mc3man/trusty-media creates=/etc/apt/sources.list.d/mc3man-trusty-media-trusty.list
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: Add libsodium repo (Ubuntu 14.04)
  command: add-apt-repository ppa:chris-lea/libsodium creates=/etc/apt/sources.list.d/chris-lea-libsodium-trusty.list
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'


- name: Add xerus-media repo (Ubuntu 16.04)
  command: add-apt-repository ppa:mc3man/xerus-media -y creates=/etc/apt/sources.list.d/mc3man-ubuntu-xerus-media-xenial.list
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: apt-get update
  apt:
    update_cache: yes



#
# Install additional packages
#
- name: Install additional packages (Ubuntu 14.04)
  package: name={{item}} state=installed
  with_items:
    - python
    - python3.5-dev
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'


- name: Install additional packages (common)
  package: name={{item}} state=installed
  with_items:
    - git
    - ffmpeg
    - libopus-dev
    - libffi-dev
    - libsodium-dev



#
# At this point, we have all repos, so check out the source
#
- name: Clone MusicBot Git Repo
  git: repo=https://github.com/Just-Some-Bots/MusicBot.git dest=/var/Musicbot


#
# Install pip modules
#
- name: Install Pip for Python 3
  package: name=python3-pip state=installed
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  tags: test

- name: Install Pip Modules
  command: python3.5 -m pip install -U -r requirements.txt chdir=/var/Musicbot
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  tags: test


- name: Install Pip for Python 3
  package: name=python3-pip state=installed
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: Install Pip Modules
  command: python3 -m pip install -U -r requirements.txt chdir=/var/Musicbot
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'



