
- name: Install starting packages
  package: name={{item}} state=installed
  with_items:
    - build-essential
    - unzip
    - software-properties-common


- name: Add xerus-media repo
  command: add-apt-repository ppa:mc3man/xerus-media -y creates=/etc/apt/sources.list.d/mc3man-ubuntu-xerus-media-xenial.list
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
  register: xerus_media_repo_installed

- name: Just installed xerus_media_repo, running apt-get update
  command: apt-get update -y
  when: xerus_media_repo_installed.stdout == "OK"

- name: Install additional packages
  package: name={{item}} state=installed
  with_items:
    - git
    - ffmpeg
    - libopus-dev
    - libffi-dev
    - libsodium-dev
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'


- name: Clone MusicBot Git Repo
  git: repo=https://github.com/Just-Some-Bots/MusicBot.git dest=/var/Musicbot


- name: Install Pip for Python 3
  package: name=python3-pip state=installed
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: Install Pip Modules
  command: python3 -m pip install -U -r requirements.txt chdir=/var/Musicbot
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'



